package run;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;

import messge.Msg;

public class Setting {

	public static void main(String[] args) {
		new Setting();
	}

	private String URL = "jdbc:mysql://localhost/?" + "ChacterEncoding=UTF-8&" + "serverTimezone=UTC&"
			+ "allowLoadLocalIncoding=true&" + "allowPublicKeyRetrieval=true&" + "allowMultiQueries=true";
	private String ID = "root";
	private String PW = "1234";
	private Connection con;
	private PreparedStatement pstmt;

	public Setting() {
		// TODO Auto-generated constructor stub
		try {
			con = DriverManager.getConnection(URL, ID, PW);
			System.out.println("con 연결 성공");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		int result = setDb("-- MySQL Script generated by MySQL Workbench\r\n" + "-- Wed Mar  1 11:11:52 2023\r\n"
				+ "-- Model: New Model    Version: 1.0\r\n" + "-- MySQL Workbench Forward Engineering\r\n" + "\r\n"
				+ "SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;\r\n"
				+ "SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;\r\n"
				+ "SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';\r\n"
				+ "\r\n" + "-- -----------------------------------------------------\r\n" + "-- Schema setting3\r\n"
				+ "-- -----------------------------------------------------\r\n"
				+ "DROP SCHEMA IF EXISTS `setting3` ;\r\n" + "\r\n"
				+ "-- -----------------------------------------------------\r\n" + "-- Schema setting3\r\n"
				+ "-- -----------------------------------------------------\r\n"
				+ "CREATE SCHEMA IF NOT EXISTS `setting3` DEFAULT CHARACTER SET utf8 ;\r\n" + "USE `setting3` ;\r\n"
				+ "\r\n" + "-- -----------------------------------------------------\r\n"
				+ "-- Table `setting3`.`user`\r\n" + "-- -----------------------------------------------------\r\n"
				+ "CREATE TABLE IF NOT EXISTS `setting3`.`user` (\r\n" + "  `u_no` INT(11) NOT NULL AUTO_INCREMENT,\r\n"
				+ "  `id` VARCHAR(20) NULL,\r\n" + "  `pw` VARCHAR(20) NULL,\r\n" + "  `name1` VARCHAR(20) NULL,\r\n"
				+ "  `name2` VARCHAR(20) NULL,\r\n" + "  `birth` DATE NULL,\r\n" + "  `mileage` INT(11) NULL,\r\n"
				+ "  PRIMARY KEY (`u_no`))\r\n" + "ENGINE = InnoDB;\r\n" + "\r\n" + "\r\n"
				+ "-- -----------------------------------------------------\r\n" + "-- Table `setting3`.`continent`\r\n"
				+ "-- -----------------------------------------------------\r\n"
				+ "CREATE TABLE IF NOT EXISTS `setting3`.`continent` (\r\n"
				+ "  `c_no` INT(11) NOT NULL AUTO_INCREMENT,\r\n" + "  `c_name` VARCHAR(10) NULL,\r\n"
				+ "  `x` INT(11) NULL,\r\n" + "  `y` INT(11) NULL,\r\n" + "  PRIMARY KEY (`c_no`))\r\n"
				+ "ENGINE = InnoDB;\r\n" + "\r\n" + "\r\n"
				+ "-- -----------------------------------------------------\r\n" + "-- Table `setting3`.`nation`\r\n"
				+ "-- -----------------------------------------------------\r\n"
				+ "CREATE TABLE IF NOT EXISTS `setting3`.`nation` (\r\n"
				+ "  `n_no` INT(11) NOT NULL AUTO_INCREMENT,\r\n" + "  `c_no` INT(11) NULL,\r\n"
				+ "  `code` VARCHAR(3) NULL,\r\n" + "  `n_name` VARCHAR(20) NULL,\r\n" + "  `x` INT(11) NULL,\r\n"
				+ "  `y` INT(11) NULL,\r\n" + "  PRIMARY KEY (`n_no`),\r\n"
				+ "  INDEX `fk_nation_continent1_idx` (`c_no` ASC) VISIBLE,\r\n"
				+ "  CONSTRAINT `fk_nation_continent1`\r\n" + "    FOREIGN KEY (`c_no`)\r\n"
				+ "    REFERENCES `setting3`.`continent` (`c_no`)\r\n" + "    ON DELETE NO ACTION\r\n"
				+ "    ON UPDATE NO ACTION)\r\n" + "ENGINE = InnoDB;\r\n" + "\r\n" + "\r\n"
				+ "-- -----------------------------------------------------\r\n" + "-- Table `setting3`.`schedule`\r\n"
				+ "-- -----------------------------------------------------\r\n"
				+ "CREATE TABLE IF NOT EXISTS `setting3`.`schedule` (\r\n"
				+ "  `s_no` INT(11) NOT NULL AUTO_INCREMENT,\r\n" + "  `date` DATE NULL,\r\n"
				+ "  `depart` INT(11) NULL,\r\n" + "  `arrival` INT(11) NULL,\r\n" + "  `departTime` TIME NULL,\r\n"
				+ "  `timeTaken` TIME NULL,\r\n" + "  `price` INT(11) NULL,\r\n" + "  PRIMARY KEY (`s_no`),\r\n"
				+ "  INDEX `fk_schedule_nation1_idx` (`depart` ASC) VISIBLE,\r\n"
				+ "  INDEX `fk_schedule_nation2_idx` (`arrival` ASC) VISIBLE,\r\n"
				+ "  CONSTRAINT `fk_schedule_nation1`\r\n" + "    FOREIGN KEY (`depart`)\r\n"
				+ "    REFERENCES `setting3`.`nation` (`n_no`)\r\n" + "    ON DELETE NO ACTION\r\n"
				+ "    ON UPDATE NO ACTION,\r\n" + "  CONSTRAINT `fk_schedule_nation2`\r\n"
				+ "    FOREIGN KEY (`arrival`)\r\n" + "    REFERENCES `setting3`.`nation` (`n_no`)\r\n"
				+ "    ON DELETE NO ACTION\r\n" + "    ON UPDATE NO ACTION)\r\n" + "ENGINE = InnoDB;\r\n" + "\r\n"
				+ "\r\n" + "-- -----------------------------------------------------\r\n"
				+ "-- Table `setting3`.`reservation`\r\n"
				+ "-- -----------------------------------------------------\r\n"
				+ "CREATE TABLE IF NOT EXISTS `setting3`.`reservation` (\r\n"
				+ "  `r_no` INT(11) NOT NULL AUTO_INCREMENT,\r\n" + "  `u_no` INT(11) NULL,\r\n"
				+ "  `s_no` INT(11) NULL,\r\n" + "  `income` INT(11) NULL,\r\n" + "  `expense` INT(11) NULL,\r\n"
				+ "  PRIMARY KEY (`r_no`),\r\n" + "  INDEX `fk_reservation_user_idx` (`u_no` ASC) VISIBLE,\r\n"
				+ "  INDEX `fk_reservation_schedule1_idx` (`s_no` ASC) VISIBLE,\r\n"
				+ "  CONSTRAINT `fk_reservation_user`\r\n" + "    FOREIGN KEY (`u_no`)\r\n"
				+ "    REFERENCES `setting3`.`user` (`u_no`)\r\n" + "    ON DELETE NO ACTION\r\n"
				+ "    ON UPDATE NO ACTION,\r\n" + "  CONSTRAINT `fk_reservation_schedule1`\r\n"
				+ "    FOREIGN KEY (`s_no`)\r\n" + "    REFERENCES `setting3`.`schedule` (`s_no`)\r\n"
				+ "    ON DELETE NO ACTION\r\n" + "    ON UPDATE NO ACTION)\r\n" + "ENGINE = InnoDB;\r\n" + "\r\n"
				+ "\r\n" + "-- -----------------------------------------------------\r\n"
				+ "-- Table `setting3`.`boarding`\r\n" + "-- -----------------------------------------------------\r\n"
				+ "CREATE TABLE IF NOT EXISTS `setting3`.`boarding` (\r\n"
				+ "  `b_no` INT(11) NOT NULL AUTO_INCREMENT,\r\n" + "  `r_no` INT(11) NULL,\r\n"
				+ "  `agegroup` INT(11) NULL,\r\n" + "  `b_name` VARCHAR(50) NULL,\r\n" + "  `birth` DATE NULL,\r\n"
				+ "  `seat` VARCHAR(3) NULL,\r\n" + "  PRIMARY KEY (`b_no`),\r\n"
				+ "  INDEX `fk_boarding_reservation1_idx` (`r_no` ASC) VISIBLE,\r\n"
				+ "  CONSTRAINT `fk_boarding_reservation1`\r\n" + "    FOREIGN KEY (`r_no`)\r\n"
				+ "    REFERENCES `setting3`.`reservation` (`r_no`)\r\n" + "    ON DELETE NO ACTION\r\n"
				+ "    ON UPDATE NO ACTION)\r\n" + "ENGINE = InnoDB;\r\n" + "\r\n" + "set global local_infile = 1;\r\n"
				+ "load data local infile './datafiles/user.txt' into table setting3.user lines terminated by '\\r' ignore 1 lines;\r\n"
				+ "load data local infile './datafiles/continent.txt' into table setting3.continent lines terminated by '\\r' ignore 1 lines;\r\n"
				+ "load data local infile './datafiles/nation.txt' into table setting3.nation lines terminated by '\\r' ignore 1 lines;\r\n"
				+ "load data local infile './datafiles/schedule.txt' into table setting3.schedule lines terminated by '\\r' ignore 1 lines;\r\n"
				+ "load data local infile './datafiles/reservation.txt' into table setting3.reservation lines terminated by '\\r' ignore 1 lines;\r\n"
				+ "load data local infile './datafiles/boarding.txt' into table setting3.boarding lines terminated by '\\r' ignore 1 lines;\r\n"
				+ "\r\n" + "drop user if exists 'user'@'localhost';\r\n"
				+ "create user 'user'@'localhost' identified by '1234';\r\n"
				+ "grant select, insert, delete, update on setting3.* to 'user'@'localhost';\r\n" + "\r\n"
				+ "SET SQL_MODE=@OLD_SQL_MODE;\r\n" + "SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;\r\n"
				+ "SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;\r\n" + "");

		if (result == -1) {
			Msg.error("셋팅 실패");
			return;
		}
		Msg.info("셋팅 성공");

	}

	public int setDb(String sql, Object... vals) {
		// TODO Auto-generated method stub
		try {
			pstmt = con.prepareStatement(sql);

			int cnt = 1;
			for (Object val : vals) {
				pstmt.setObject(cnt++, val);
			}

			System.out.println("setDb 성공");
			return pstmt.executeUpdate();

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.out.println("setDb 실패");
			return -1;
		}
	}

	public Vector<Vector<String>> getDb(String sql, Object... vals) {
		// TODO Auto-generated method stub
		Vector<Vector<String>> data = new Vector<Vector<String>>();
		try {
			pstmt = con.prepareStatement(sql);

			int cnt = 1;
			for (Object val : vals) {
				pstmt.setObject(cnt++, val);
			}

			ResultSet rs = pstmt.executeQuery();
			ResultSetMetaData rsmd = rs.getMetaData();

			while (rs.next()) {

				Vector<String> row = new Vector<String>();
				for (int i = 0; i < rsmd.getColumnCount(); i++) {
					row.add(rs.getObject(i + 1) + "");

				}

				data.add(row);
			}
			System.out.println("getDb 성공");

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			System.out.println("getDb 실패");
			return null;
		}
		return data;
	}
}
