-- MySQL Script generated by MySQL Workbench
-- Wed Mar  1 11:11:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema setting3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `setting3` ;

-- -----------------------------------------------------
-- Schema setting3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `setting3` DEFAULT CHARACTER SET utf8 ;
USE `setting3` ;

-- -----------------------------------------------------
-- Table `setting3`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setting3`.`user` (
  `u_no` INT(11) NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(20) NULL,
  `pw` VARCHAR(20) NULL,
  `name1` VARCHAR(20) NULL,
  `name2` VARCHAR(20) NULL,
  `birth` DATE NULL,
  `mileage` INT(11) NULL,
  PRIMARY KEY (`u_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `setting3`.`continent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setting3`.`continent` (
  `c_no` INT(11) NOT NULL AUTO_INCREMENT,
  `c_name` VARCHAR(10) NULL,
  `x` INT(11) NULL,
  `y` INT(11) NULL,
  PRIMARY KEY (`c_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `setting3`.`nation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setting3`.`nation` (
  `n_no` INT(11) NOT NULL AUTO_INCREMENT,
  `c_no` INT(11) NULL,
  `code` VARCHAR(3) NULL,
  `n_name` VARCHAR(20) NULL,
  `x` INT(11) NULL,
  `y` INT(11) NULL,
  PRIMARY KEY (`n_no`),
  INDEX `fk_nation_continent1_idx` (`c_no` ASC) VISIBLE,
  CONSTRAINT `fk_nation_continent1`
    FOREIGN KEY (`c_no`)
    REFERENCES `setting3`.`continent` (`c_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `setting3`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setting3`.`schedule` (
  `s_no` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `depart` INT(11) NULL,
  `arrival` INT(11) NULL,
  `departTime` TIME NULL,
  `timeTaken` TIME NULL,
  `price` INT(11) NULL,
  PRIMARY KEY (`s_no`),
  INDEX `fk_schedule_nation1_idx` (`depart` ASC) VISIBLE,
  INDEX `fk_schedule_nation2_idx` (`arrival` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_nation1`
    FOREIGN KEY (`depart`)
    REFERENCES `setting3`.`nation` (`n_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_nation2`
    FOREIGN KEY (`arrival`)
    REFERENCES `setting3`.`nation` (`n_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `setting3`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setting3`.`reservation` (
  `r_no` INT(11) NOT NULL AUTO_INCREMENT,
  `u_no` INT(11) NULL,
  `s_no` INT(11) NULL,
  `income` INT(11) NULL,
  `expense` INT(11) NULL,
  PRIMARY KEY (`r_no`),
  INDEX `fk_reservation_user_idx` (`u_no` ASC) VISIBLE,
  INDEX `fk_reservation_schedule1_idx` (`s_no` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_user`
    FOREIGN KEY (`u_no`)
    REFERENCES `setting3`.`user` (`u_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_schedule1`
    FOREIGN KEY (`s_no`)
    REFERENCES `setting3`.`schedule` (`s_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `setting3`.`boarding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setting3`.`boarding` (
  `b_no` INT(11) NOT NULL AUTO_INCREMENT,
  `r_no` INT(11) NULL,
  `agegroup` INT(11) NULL,
  `b_name` VARCHAR(50) NULL,
  `birth` DATE NULL,
  `seat` VARCHAR(3) NULL,
  PRIMARY KEY (`b_no`),
  INDEX `fk_boarding_reservation1_idx` (`r_no` ASC) VISIBLE,
  CONSTRAINT `fk_boarding_reservation1`
    FOREIGN KEY (`r_no`)
    REFERENCES `setting3`.`reservation` (`r_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

set global local_infile = 1;
load data local infile './datafiles/user.txt' into table setting3.user lines terminated by '\r' ignore 1 lines;
load data local infile './datafiles/continent.txt' into table setting3.continent lines terminated by '\r' ignore 1 lines;
load data local infile './datafiles/nation.txt' into table setting3.nation lines terminated by '\r' ignore 1 lines;
load data local infile './datafiles/schedule.txt' into table setting3.schedule lines terminated by '\r' ignore 1 lines;
load data local infile './datafiles/reservation.txt' into table setting3.reservation lines terminated by '\r' ignore 1 lines;
load data local infile './datafiles/boarding.txt' into table setting3.boarding lines terminated by '\r' ignore 1 lines;

drop user if exists 'user'@'localhost';
create user 'user'@'localhost' identified by '1234';
grant select, insert, delete, update on setting3.* to 'user'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
